posts/urls.py
from django.urls import path
from .views import (
    post_list_and_create,
    load_post_data_view,
    like_unlike_post,
    post_detail,
    post_detail_data_view,
    update_post,
    delete_post,
    image_upload_view, 
    add_comment
    
)

app_name= 'posts'

urlpatterns = [
    path('', post_list_and_create, name='main-board'),
    path('like-unlike/', like_unlike_post, name='like-unlike'),
    path('upload/', image_upload_view, name='image-upload'),
    path('<pk>/', post_detail, name='post-detail'),
    path('<pk>/update/', update_post, name='post-update'),
    path('<pk>/delete/', delete_post, name='post-delete'),
    path('add_comment/<int:pk>/', add_comment, name='add_comment'),

    path('data/<int:num_posts>/', load_post_data_view, name='posts-data'),
    path('<pk>/data/', post_detail_data_view, name='post-detail-data'),

    
]

posts_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    liked = models.ManyToManyField(User, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)


    @property
    def like_count(self):
        return self.liked.all().count()  

    def get_photos(self):
        return self.photo_set.all()    


    class Meta:
        ordering = ("-created",)   


class Photo(models.Model):
        post = models.ForeignKey(Post, on_delete=models.CASCADE)
        image = models.ImageField(upload_to="photos")
        created = models.DateTimeField(auto_now_add=True)

        def __str__(self):
            return f"{self.post.title}-{self.pk}"  


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post.title}'

  

posts/views.py
from django.shortcuts import render
from .models import Post, Photo, Comment
from django.http import JsonResponse, HttpResponse
from .forms import PostForm
from profiles.models import Profile
from .utils import action_permission
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

# from django.core import serializers
# Create your views here.

@login_required
def post_list_and_create(request):
    form = PostForm(request.POST or None)
    # qs = Post.objects.all()

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        if form.is_valid():
            author = Profile.objects.get(user=request.user)
            instance = form.save(commit=False)
            instance.author = author
            instance.save()
            data = {
                'id': instance.id,
                'title': instance.title,
                'body': instance.body,
                'author': instance.author.user.username,
                # Add any other post data you want to send to the template
            }
            return JsonResponse(data, safe=False)
        else:
            return JsonResponse({'error': form.errors}, status=400)
            

    context = {
        'form': form,
    }

    return render(request, 'posts/main.html', context)

@login_required
def post_detail(request, pk):
    obj = Post.objects.get(pk=pk)
    form = PostForm()

    context = {
        'obj': obj,
        'form': form,
    } 

    return render(request, 'posts/detail.html', context) 

@login_required
def load_post_data_view(request, num_posts):
        visible = 3
        upper = num_posts
        lower = upper - visible
        size = Post.objects.all().count()

        qs = Post.objects.all()
        data = []
        for obj in qs:
            item = {
                'id': obj.id,
                'title': obj.title,
                'body': obj.body,
                'liked': 'True' if request.user in obj.liked.all() else 'False',  
                'count': obj.like_count,  
                'author': obj.author.user.username  
            }
            data.append(item)

        return JsonResponse({'data': data[lower:upper], 'size': size})
    
@login_required
def post_detail_data_view(request, pk):
    obj = Post.objects.get(pk=pk)
    data = {
        'id': obj.id,
        'title': obj.title,
        'body': obj.body,
        'author': obj.author.user.username,
        'avatar': obj.author.avatar.url,
        'logged_in': request.user.username,
    }
    return JsonResponse({'data': data})
    

@login_required
def like_unlike_post(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        # This is an AJAX request
        pk = request.POST.get('pk')
        obj = Post.objects.get(pk=pk)
        if request.user in obj.liked.all():
            liked=False
            obj.liked.remove(request.user)
        else:
            liked=True
            obj.liked.add(request.user)
        return JsonResponse({'liked': liked, 'count': obj.like_count})
    else:
        # This is not an AJAX request
        return JsonResponse({'error': 'Not an AJAX request'}, status=400) 
    

@login_required
@action_permission
def update_post(request, pk):
    obj = Post.objects.get(pk=pk)
    
    # Manually check for 'X-Requested-With' header
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        new_title = request.POST.get('title')
        new_body = request.POST.get('body')
        obj.title = new_title
        obj.body = new_body
        obj.save()
        
        return JsonResponse({
            'title': new_title,
            'body': new_body,
        })
    else:
        return HttpResponseBadRequest('Not an AJAX request')


@login_required
@action_permission
def delete_post(request, pk):
    obj = Post.objects.get(pk=pk)

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        obj.delete()
        return JsonResponse({'post has been deleted'})
    else:
        # Handle the case for non-AJAX requests, if necessary
        return HttpResponseBadRequest('Not an AJAX request')


@login_required
def image_upload_view(request):
    if request.method == 'POST':
        img = request.FILES.get('file')
        new_post_id = request.POST.get('new_post_id')
        post = Post.objects.get(id=new_post_id)
        Photo.objects.create(image=img, post=post)
    return HttpResponse()    


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        content = request.POST.get('comment')
        comment = Comment.objects.create(post=post, user=request.user, content=content)
        
        # Return the username and comment for the newly added comment
        return JsonResponse({
            'username': request.user.username,
            'comment': content,
        }, safe=False)

posts/templates/posts/detail.html
{% extends "base.html"%}
{% load static %}

{% block scripts %}
    <script src="{% static 'posts/detail.js' %}" defer></script>
{% endblock scripts %}

{% block title %}{{obj.title}} detail{% endblock title %}

{% block content %}
    <!--update modal-->
    <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Update Post</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="alert-box"></div>
            <form id="update-form">
            {% csrf_token %}
            {{form.as_p}}
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
                    <button type="submit" class="btn btn-success">update</button>
                </div>
                </form>
            </div>
        </div>
        </div>
    </div>


    <!--delete modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Post</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete <b>"{{obj.title}}"</b> ?
            </div>
            <div class="modal-footer">
                <form id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
                    <button type="submit" class="btn btn-success">delete</button>
                </form>
            </div>
        </div>
        </div>
    </div>
    


    <!--Carousel-->
    {% if obj.get_photos %}

        <div id="carouselExampleControls" class="carousel slide mb-2" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for p in obj.get_photos %}
                    <div class="carousel-item {% if forloop.counter == 1%}active{% endif %}">
                        <img src="{{p.image.url}}" class="d-block w-100" alt="photo {{obj.pk}}">
                    </div>
                {% endfor %}

            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>

    {% else %}
       <div class="mt-2 mb-2">No photos to show</div>
    {% endif %}



    <a href="{% url 'posts:main-board' %}" id="back-btn" class="btn btn-info">back</a>
    <button id="update-btn" class="btn btn-primary not-visible" data-bs-toggle="modal" data-bs-target="#updateModal">update</button>
    <button id="delete-btn" class="btn btn-danger not-visible" data-bs-toggle="modal" data-bs-target="#deleteModal">delete</button>
        <div id="spinner-box" class="text-center">
            <div class = "spinner-border" role="status"></div>

        </div>
        <div class="mt-1" id="post-box"></div>



        <form id="comment-form" method="post" data-url="{% url 'posts:add_comment' obj.pk %}">
            {% csrf_token %}
            <textarea id="comment-input" name="comment" placeholder="Leave a comment..." required></textarea>
            <button type="submit">Add Comment</button>
        </form>
        
        <!-- Comments Section -->
        <div id="comments-section">
            <h3>Comments:</h3> 
            <div class="comment">
                <strong>{{ comment.user.username }}</strong>
                <p>{{ comment.content }}</p>
            </div>           
            <p>No comments yet.</p>
            
        </div>
        
        

{% endblock content %}

posts/templates/posts/main.html
{% extends "base.html"%}

{% load static %}
<!-- {% load crispy_forms_tags %} -->

{% block scripts %}
<script src="{% static 'posts/main.js' %}" defer ></script>
{% endblock scripts %}

{% block title %}
posts
{% endblock title %}

{% block content %}
    <!-- Modal -->
    <div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Create Post</h1>
            <button type="button" class="btn-close add-modal-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="post-form" autocomplete="off">
             {% csrf_token %}
             {{form.as_p}}
               <div class="modal-footer">
                  <button type="button" class="btn btn-danger add-modal-close" data-bs-dismiss="modal">close</button>
                  <button type="submit" id="add-btn" class="btn btn-success">+ add</button>
                </div>
               </form>
               <form action="upload/" id="my-dropzone" class="dropzone dz not-visible">
                 {% csrf_token %}
                 <div class="fallback">
                   <input name="file" type="file" multiple />
                 </div>
   
               </form>
          </div>
        </div>
      </div>
    </div>
   
    <div id="alert-box"></div>
    
      <!-- Button trigger modal -->
   <button type="button" class="btn btn-info mb-2" data-bs-toggle="modal" data-bs-target="#addPostModal">
      add post
    </button>
    
   
    <div id="posts-box"></div>   
   
    <div id="spinner-box" class="text-center">
       <div class = "spinner-border" role="status"></div>
   
      </div>
     
    <div class="text-center mb-3" id="end-box">
       <button class="btn btn-primary" id="load-btn">Load More</button>
           
    </div>

{% endblock content %}